# GITHUB_PAT=ghp_xxxxxxx docker compose up --build
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: copilot-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=hiFc1SbV
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - copilot-network

  grafana:
    image: grafana/grafana:latest
    container_name: copilot-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - elasticsearch
    networks:
      - copilot-network

  python-updater:
    build:
      context: ./src/cpuad-updater
      dockerfile: Dockerfile
    container_name: copilot-updater
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASS=hiFc1SbV
      - GITHUB_PAT=${GITHUB_PAT}
      - ORGANIZATION_SLUGS=${ORGANIZATION_SLUGS}
    depends_on:
      - elasticsearch
    networks:
      - copilot-network

volumes:
  elasticsearch_data:
  grafana_data:

networks:
  copilot-network:
    driver: bridge